/* Seed Data for YBVC Canteen Ordering System
 * Includes sample products, demo accounts, pickup slots, and blog posts
 */

import { Product, PickupSlot, BlogPost, User } from './types';

export const DEMO_USERS: User[] = [
  {
    id: 'customer-1',
    email: 'student@ybvc.edu',
    password: 'password123',
    name: 'Maria Santos',
    role: 'customer',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'admin-1',
    email: 'admin@ybvc.edu',
    password: 'admin123',
    name: 'John Administrator',
    role: 'admin',
    createdAt: new Date().toISOString(),
  },
];

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Single Shot Espresso',
    description: 'Bold and intense single shot of freshly pulled espresso',
    category: 'Espresso',
    roastLevel: 'Dark',
    basePrice: 45,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/espresso-shot-9d3LkXtF5g4aZLwQqDE8VE.webp',
    available: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Double Shot Espresso',
    description: 'Rich double shot for those who need an extra kick',
    category: 'Espresso',
    roastLevel: 'Dark',
    basePrice: 65,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/espresso-shot-9d3LkXtF5g4aZLwQqDE8VE.webp',
    available: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Americano',
    description: 'Espresso shots topped with hot water for a smooth, full-bodied cup',
    category: 'Brewed',
    roastLevel: 'Medium',
    basePrice: 55,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/cappuccino-jyULSf4rpL8BwRETvz3Yby.webp',
    available: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Cappuccino',
    description: 'Creamy blend of espresso, steamed milk, and velvety foam',
    category: 'Brewed',
    roastLevel: 'Medium',
    basePrice: 75,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/cappuccino-jyULSf4rpL8BwRETvz3Yby.webp',
    available: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Latte',
    description: 'Smooth and creamy with espresso and steamed milk',
    category: 'Brewed',
    roastLevel: 'Light',
    basePrice: 75,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/cappuccino-jyULSf4rpL8BwRETvz3Yby.webp',
    available: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-6',
    name: 'Iced Americano',
    description: 'Refreshing cold espresso with ice and water',
    category: 'Iced Coffee',
    roastLevel: 'Dark',
    basePrice: 60,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/iced-coffee-Z72EDJH3xqB4FgdFhUNJ7G.webp',
    available: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    name: 'Iced Latte',
    description: 'Creamy cold latte perfect for warm afternoons',
    category: 'Iced Coffee',
    roastLevel: 'Light',
    basePrice: 80,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/iced-coffee-Z72EDJH3xqB4FgdFhUNJ7G.webp',
    available: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    name: 'Caramel Macchiato',
    description: 'Sweet caramel with espresso and steamed milk',
    category: 'Specialty Drinks',
    roastLevel: 'Medium',
    basePrice: 95,
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/iced-coffee-Z72EDJH3xqB4FgdFhUNJ7G.webp',
    available: true,
    createdAt: new Date().toISOString(),
  },
];

export const PICKUP_SLOTS: PickupSlot[] = [
  { id: 'slot-1', time: '08:00 AM', capacity: 10, reserved: 0, available: true },
  { id: 'slot-2', time: '08:30 AM', capacity: 10, reserved: 0, available: true },
  { id: 'slot-3', time: '09:00 AM', capacity: 10, reserved: 0, available: true },
  { id: 'slot-4', time: '09:30 AM', capacity: 10, reserved: 0, available: true },
  { id: 'slot-5', time: '10:00 AM', capacity: 10, reserved: 0, available: true },
  { id: 'slot-6', time: '12:00 PM', capacity: 15, reserved: 0, available: true },
  { id: 'slot-7', time: '12:30 PM', capacity: 15, reserved: 0, available: true },
  { id: 'slot-8', time: '01:00 PM', capacity: 15, reserved: 0, available: true },
  { id: 'slot-9', time: '03:00 PM', capacity: 10, reserved: 0, available: true },
  { id: 'slot-10', time: '03:30 PM', capacity: 10, reserved: 0, available: true },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'The Art of Coffee Roasting',
    excerpt: 'Discover how different roast levels bring out unique flavors in coffee beans.',
    content: `Coffee roasting is both an art and a science. The roasting process transforms green coffee beans into the aromatic brown beans we know and love. Light roasts preserve more of the bean's original characteristics, while dark roasts develop deeper, bolder flavors. Our canteen offers a variety of roast levels to suit every palate.`,
    date: '2024-03-15',
    author: 'Coffee Expert',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/coffee-roasting-XRaWLUHKvGjn2UzoXRohRV.webp',
  },
  {
    id: 'blog-2',
    title: 'Perfect Your Espresso Technique',
    excerpt: 'Learn the secrets to pulling the perfect shot of espresso every time.',
    content: `A perfect espresso shot requires precision, timing, and quality beans. The ideal extraction time is between 25-30 seconds, and the water temperature should be around 90-96°C. Consistency in tamping pressure and grind size are crucial for achieving that perfect crema and balanced flavor profile.`,
    date: '2024-03-10',
    author: 'Barista Master',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/espresso-shot-9d3LkXtF5g4aZLwQqDE8VE.webp',
  },
  {
    id: 'blog-3',
    title: 'Coffee and Productivity: A Student\'s Guide',
    excerpt: 'How to use coffee wisely to boost your study sessions and academic performance.',
    content: `For students, coffee can be a valuable tool for maintaining focus during long study sessions. However, timing is key—consuming coffee too late in the day can interfere with sleep. Aim for your caffeine intake in the morning or early afternoon, and remember that moderation is important for long-term health and productivity.`,
    date: '2024-03-05',
    author: 'Wellness Coach',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/coffee-study-79bdRx9Huzg7UZnRLhtyjv.webp',
  },
  {
    id: 'blog-4',
    title: 'Sustainable Coffee: Our Commitment',
    excerpt: 'How we source ethically and support coffee farmers around the world.',
    content: `We believe in supporting sustainable coffee farming practices. Our canteen partners with fair-trade suppliers who ensure that coffee farmers receive fair compensation for their work. By choosing our coffee, you're not just enjoying a great cup—you're supporting communities and sustainable agriculture.`,
    date: '2024-02-28',
    author: 'Sustainability Officer',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/cappuccino-jyULSf4rpL8BwRETvz3Yby.webp',
  },
  {
    id: 'blog-5',
    title: 'Milk Alternatives: Beyond Dairy',
    excerpt: 'Explore different milk options and how they complement your favorite coffee drinks.',
    content: `Whether you prefer dairy milk, oat milk, almond milk, or soy milk, each option brings something unique to your coffee. Oat milk froths beautifully for cappuccinos, almond milk adds a subtle nuttiness, and soy milk provides a creamy texture. Experiment to find your perfect match!`,
    date: '2024-02-20',
    author: 'Coffee Enthusiast',
    image: 'https://d2xsxph8kpxj0f.cloudfront.net/310519663380090351/2WXpZTFycpMWkwyo2rxMh9/cappuccino-jyULSf4rpL8BwRETvz3Yby.webp',
  },
];
